# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_time', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=10)),
                ('editor', models.CharField(max_length=50)),
                ('reporter', models.CharField(max_length=50)),
                ('graphic_explanation', models.CharField(max_length=500)),
                ('is_data_provided', models.CharField(max_length=3)),
                ('inline_or_standalone', models.CharField(max_length=11)),
                ('graphics_categories', models.CharField(max_length=15)),
            ],
        ),
    ]
