# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfxskedapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='graphics_categories',
            new_name='graphics_category',
        ),
    ]
